
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int INT = 12;
  public static final int DIVIDE = 3;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int TYINT = 8;
  public static final int ID = 11;
  public static final int ASSIGN = 7;
  public static final int error = 1;
  public static final int PRINT = 10;
  public static final int TYFLOAT = 9;
  public static final int TIMES = 4;
  public static final int FLOAT = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "DIVIDE",
  "TIMES",
  "PLUS",
  "MINUS",
  "ASSIGN",
  "TYINT",
  "TYFLOAT",
  "PRINT",
  "ID",
  "INT",
  "FLOAT"
  };
}

